name: pylint/pytest

on:
  push:
    branches:
      main
  pull_request:

jobs:

  build_env:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        python-ver:
          - "3.11"
          - "latest"

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda
        uses: ./.github/actions/cache-conda
        with:
          python-ver: ${{ matrix.python-ver }}


  pytest:
    needs: build_env
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        python-ver:
          - "3.11"
          - "latest"

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda
        uses: ./.github/actions/cache-conda
        with:
          python-ver: ${{ matrix.python-ver }}

      - name: Install pytest/coverage
        run: |
          conda install conda-forge::pytest conda-forge::pytest-cov

      - name: Pytest
        run: |
          # Need to be set to properly initialize the terminal for curses
          export TERM=xterm-256color
          export TERMINFO=/usr/share/terminfo
          script -q -e -a -c "pytest --cov --cov-report xml"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage1.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  pylint:
    needs: build_env
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        python-ver:
          - "3.11"
          - "latest"

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda
        uses: ./.github/actions/cache-conda
        with:
          python-ver: ${{ matrix.python-ver }}

      - name: Install pylint
        run: pip install pylint

      - name: Pylint
        run: pylint ./**/*.py
